// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOQxElb09Xq5dwyXfFT1EWTxcs-p6rsf0',
    appId: '1:403947382195:web:699c25de8cc8b7429857c6',
    messagingSenderId: '403947382195',
    projectId: 'bomberos-alerta-app',
    authDomain: 'bomberos-alerta-app.firebaseapp.com',
    storageBucket: 'bomberos-alerta-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR7ue-7xTT56X-2Fto7J-fUL_csV9wons',
    appId: '1:403947382195:android:114bdb4508c0035b9857c6',
    messagingSenderId: '403947382195',
    projectId: 'bomberos-alerta-app',
    storageBucket: 'bomberos-alerta-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgZsNmUjfrJtRURLlZ6q1iG-AHADM42pc',
    appId: '1:403947382195:ios:ebaee447e84d99599857c6',
    messagingSenderId: '403947382195',
    projectId: 'bomberos-alerta-app',
    storageBucket: 'bomberos-alerta-app.firebasestorage.app',
    iosBundleId: 'com.example.bomberosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgZsNmUjfrJtRURLlZ6q1iG-AHADM42pc',
    appId: '1:403947382195:ios:ebaee447e84d99599857c6',
    messagingSenderId: '403947382195',
    projectId: 'bomberos-alerta-app',
    storageBucket: 'bomberos-alerta-app.firebasestorage.app',
    iosBundleId: 'com.example.bomberosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOQxElb09Xq5dwyXfFT1EWTxcs-p6rsf0',
    appId: '1:403947382195:web:6a28533db3a167579857c6',
    messagingSenderId: '403947382195',
    projectId: 'bomberos-alerta-app',
    authDomain: 'bomberos-alerta-app.firebaseapp.com',
    storageBucket: 'bomberos-alerta-app.firebasestorage.app',
  );

}